#!/bin/ash

# System Startup Script
# 

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/bin/mount -t tmpfs /tmp /tmp
/bin/mount -t tmpfs -o mode=0755 none /dev
/bin/mkdir /dev/pts
/bin/mkdir /dev/shm
/bin/mount -t tmpfs -o mode=0755 /var /var
for x in cache lib lib/misc lib/locate local lock log mail opt run spool; do mkdir /var/$x; done
ln -s ../tmp /var/tmp

echo -n "Starting mdev: "
/sbin/mdev -s

echo -n "Mounting devpts: "
mount /dev/pts
check_status

if [ -x /sbin/hwclock ] && [ -e /dev/rtc ]; then
	echo -n "Setting system clock: "
	hwclock --hctosys --utc
fi

if [ -x /sbin/fsck ]; then
	echo "Starting fsck for local filesystems."
	fsck -A -C -R -T -t nonfs,nosmbfs
	if [ "$?" -gt 2 ]; then
		echo "WARNING: Errors found while checking filesystems."
		echo "You can login as root now, the system will reboot after logout."
		sulogin
		reboot
	elif [ "$?" = "2" ]; then
		echo "NOTICE: System needs to be rebooted now."
		sleep 1
		reboot
	else
		echo -n "Checking local filesystems: "
	fi
fi


if [ -x /sbin/swapon ]; then
	echo -n "Enabling swap space: "
	swapon -a
fi

echo -n "Remounting root rw: "
mount -o remount,rw /

echo -n "Setting hostname: "
echo "acrlinux">/etc/hostname
hostname acrlinux

echo -n "Cleaning up system: "
> /var/run/utmp
touch /var/log/wtmp
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0660 /var/log/messages
rm -rf /tmp/*
rm -f /var/run/*.pid

echo -n "Setting up interface lo: "
ifconfig lo up 127.0.0.1

echo -n "setting eth0 ip"
ifconfig eth0 up

#echo "Running start scripts."

#runlevel=S
#prevlevel=N
#umask 022
#export runlevel prevlevel 
#trap ":" INT QUIT TSTP


#  for i in /etc/rcS.d/S??*
#  do
#     [ ! -f  "$i" ] && continue;
#     $i start       
#  done

exit 0
